# Generated by Django 6.0.6 on 2026-07-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='schema_code',
            field=models.TextField(blank=True, default='Table User {\n  id int [pk]\n  name varchar\n}'),
        ),
    ]
